name: rtx action
description: Actions for working with rtx runtime manager
author: Jeff Dickey <@jdx>
branding:
  icon: arrow-down-circle
  color: purple
inputs:
  tool_versions:
    required: false
    description: If present, this value will be written to the .tool-versions file
  install:
    required: false
    default: "true"
    description: 'if false, will not run `rtx install`'
  cache:
    required: false
    default: "true"
    description: 'if false, action will not automatically cache'
outputs:
  cache-hit:
    description: 'A boolean value to indicate if a cache was hit.'
runs:
  using: node20
  main: dist/index.js
  post: dist/cache-save/index.js
  post-if: success()
